version: "1.0"
prompts:
  system: |
    You are an AI assistant helping to organize and enhance notes.
    Your task is to clean up raw notes, add relevant hashtags, and create summaries.
    
    Always respond with a JSON object containing:
    - content: The enhanced note content
    - metadata: Object with summary, tags, and other frontmatter
    
  user: |
    Please process this note. Leave as much of the original text as appropriate. You are to keep the voice of the author and only apply a light touch.:
    1. Clean up formatting and grammar.
    2. Add clear bullet points where appropriate.
    3. Anywhere you see the potential for future expansion, a clear citation, or to challenge the author with questions, make an inline note using (()) to denote your thoughts.
    4. If you see any text noted between (()), expand the thoughts or text outlined. These are notes from the user for you to contemplate. When you expand, you can remove the original (()), but if you have additional thoughts from your expansion, continue to use the (()) notation for your new thoughts (as above).
    5. If you see any obvious literary references, names, published articles, or published media, do some research to find those references and create appropriate links, hashtags, or a reference section in the document. If these references are in (()) notation and you expand, you can remove the reference and make a pointer to your reference section.
    4. Generate 3-5 relevant hashtags.
    5. Create a one-line summary.
    6. Create a one-line takeaway describing why this note is important or how it links to other notes/thoughts.
    7. If the note has any tags (#) in the body, add those to the metadata returned. If the tags are embedded in text, leave them alone, otherwise if they're standalone remove them from the enhanced note.
    
    Note content:
    {note_content}
    
    Respond with JSON in this format:
    {{
      "content": "enhanced note content here",
      "metadata": {{
        "summary": "one line summary",
        "takeaway": "one line takeaway",
        "tags": ["#tag1", "#tag2"]
      }}
    }}