name: Process Notes

on:
  # schedule:
  #   # Run every 10 minutes
  #   - cron: '*/10 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  process:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create Google Drive credentials
      run: |
        echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" | base64 -d > /tmp/gcp-key.json
    
    - name: Run note processor
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        GOOGLE_DRIVE_CREDENTIALS_PATH: /tmp/gcp-key.json
        GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
      run: |
        python src/main.py
    
    - name: Clean up credentials
      if: always()
      run: |
        rm -f /tmp/gcp-key.json